// src/components/Button.vue
<template>
	<a
		:class="`mdc-button mdc-ripple-upgraded ${
			blok.type ? 'mdc-button--' + blok.type : ''
		}`"
	>
		<i
			v-if="blok.icon"
			v-html="blok.icon"
			aria-hidden="true"
			class="mdc-button__icon"
		/>
		<span class="mdc-button__label">{{ blok.label }}</span>
		<div class="mdc-button__ripple"></div>
	</a>
</template>

<script>
export default {
	name: "Button",
	props: ["blok"],
};
</script>

// src/components/Button.jsx
export default function Button(props) {
	return (
		<a
			className={`mdc-button mdc-ripple-upgraded ${
				props.type ? 'mdc-button--' + props.type : ''
			}`}
		>
			{props.icon && (
				<i ariaHidden="true" className="mdc-button__icon">
					{props.icon}
				</i>
			)}
			<span className="mdc-button__label">{props.blok.label}</span>
			<div className="mdc-button__ripple"></div>
		</a>
	)
}
